#!/usr/bin/env python3
"""SIGNAL thumbnail compositor. Spec-driven (thumbs.json): background image (generated by
Higgsfield or a reused plate) + crisp overlays via Pillow — scrim, Anton hook headline with
glow+stroke, optional subtext, SIGNAL wordmark, SIGNAL/NOISE verdict meter, extras (question
mark / target circle / arrow). Renders 1280x720 JPEG (<2MB, YouTube-ready)."""
import os, sys, json, math
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageOps, ImageChops

HERE = os.path.dirname(os.path.abspath(__file__))
SCRATCH = "/tmp/claude-0/-home-user-YOutube/49ca386a-7ebb-5a62-a8e4-ca474812989b/scratchpad"
FONTS = os.path.join(SCRATCH, "fonts")
W, H = 1280, 720

# fonts
ANTON = os.path.join(FONTS, "Anton-Regular.ttf")
ARCHIVO = os.path.join(FONTS, "ArchivoBlack-Regular.ttf")
FMB = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
FM = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

COLORS = {
    "cyan":  (46, 224, 232),
    "amber": (242, 178, 76),
    "white": (238, 244, 251),
    "red":   (233, 86, 78),
}
INK = (233, 239, 247)
MUT = (168, 190, 208)
CY = (46, 224, 232)
NOISE = (242, 178, 76)


def font(p, s):
    return ImageFont.truetype(p, s)


def fit_bg(path):
    im = Image.open(path).convert("RGB")
    return ImageOps.fit(im, (W, H), method=Image.LANCZOS, centering=(0.5, 0.45))


def vignette(im, strength=0.55):
    mask = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(mask)
    d.ellipse([-W*0.25, -H*0.25, W*1.25, H*1.25], fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(180))
    dark = Image.new("RGB", (W, H), (0, 0, 0))
    inv = ImageChops.invert(mask).point(lambda x: int(x*strength))
    return Image.composite(dark, im, inv)


def side_scrim(im, side, frac=0.62, power=205):
    """Gradient darken one side/edge so text reads. side in tl,tr,bl,br,top,bottom,left,right,center."""
    grad = Image.new("L", (W, H), 0)
    px = grad.load()
    for y in range(H):
        for x in range(0, W, 2):
            fx = x / W; fy = y / H
            if side == "left":   a = max(0, 1 - fx / frac)
            elif side == "right":a = max(0, 1 - (1 - fx) / frac)
            elif side == "top":  a = max(0, 1 - fy / frac)
            elif side == "bottom":a = max(0, 1 - (1 - fy) / frac)
            elif side == "tl":   a = max(0, 1 - (fx**2 + fy**2)**0.5 / frac)
            elif side == "tr":   a = max(0, 1 - (((1-fx))**2 + fy**2)**0.5 / frac)
            elif side == "bl":   a = max(0, 1 - (fx**2 + (1-fy)**2)**0.5 / frac)
            elif side == "br":   a = max(0, 1 - (((1-fx))**2 + (1-fy)**2)**0.5 / frac)
            else:                a = 0
            v = int(min(1, a) * power)
            px[x, y] = v; px[min(x+1, W-1), y] = v
    grad = grad.filter(ImageFilter.GaussianBlur(40))
    dark = Image.new("RGB", (W, H), (2, 5, 9))
    return Image.composite(dark, im, grad)


def autofit(text, fpath, box_w, box_h, start=200, min_s=54, tracking=0):
    """largest size that fits text (<=2 lines) in box."""
    words = text.split()
    for s in range(start, min_s - 1, -2):
        fo = font(fpath, s)
        # try 1 line
        w1 = line_w(text, fo, tracking)
        if w1 <= box_w and s * 1.15 <= box_h:
            return fo, [text], s
        # try 2 lines: best split
        best = None
        for i in range(1, len(words)):
            l1 = " ".join(words[:i]); l2 = " ".join(words[i:])
            wmax = max(line_w(l1, fo, tracking), line_w(l2, fo, tracking))
            if wmax <= box_w and s * 2 * 1.15 <= box_h:
                if best is None or wmax < best[2]:
                    best = ([l1, l2], s, wmax)
        if best:
            return fo, best[0], s
    fo = font(fpath, min_s)
    return fo, [text], min_s


def line_w(t, fo, tracking=0):
    d = ImageDraw.Draw(Image.new("RGB", (10, 10)))
    b = d.textbbox((0, 0), t, font=fo)
    return (b[2] - b[0]) + tracking * max(0, len(t) - 1)


def draw_text_track(d, xy, t, fo, fill, tracking=0):
    x, y = xy
    for ch in t:
        d.text((x, y), ch, font=fo, fill=fill)
        b = d.textbbox((0, 0), ch, font=fo)
        x += (b[2] - b[0]) + tracking


def glow_text(base, lines, fo, xy, fill, glow, stroke=(6, 8, 12), line_gap=1.06,
              align="left", stroke_w=None, tracking=0):
    """Draw multiline headline with outer glow + dark stroke, high pop."""
    if stroke_w is None:
        stroke_w = max(6, fo.size // 14)
    asc = fo.size
    x0, y0 = xy
    # measure
    widths = [line_w(t, fo, tracking) for t in lines]
    lh = int(asc * line_gap)
    total_h = lh * len(lines)
    # glow layer
    gl = Image.new("RGBA", base.size, (0, 0, 0, 0))
    gd = ImageDraw.Draw(gl)
    for i, t in enumerate(lines):
        w = widths[i]
        if align == "center":  lx = x0 - w // 2
        elif align == "right": lx = x0 - w
        else:                  lx = x0
        ly = y0 + i * lh
        draw_text_track(gd, (lx, ly), t, fo, tuple(glow) + (255,), tracking)
    gl = gl.filter(ImageFilter.GaussianBlur(max(6, fo.size // 9)))
    # boost glow
    a = gl.split()[3].point(lambda p: min(255, int(p * 2.0)))
    gl.putalpha(a)
    base.alpha_composite(gl)
    base.alpha_composite(gl)  # twice for punch
    # sharp text w/ stroke
    td = ImageDraw.Draw(base)
    for i, t in enumerate(lines):
        w = widths[i]
        if align == "center":  lx = x0 - w // 2
        elif align == "right": lx = x0 - w
        else:                  lx = x0
        ly = y0 + i * lh
        if tracking:
            # stroke via manual offsets per char
            for dx in range(-stroke_w, stroke_w + 1, 2):
                for dy in range(-stroke_w, stroke_w + 1, 2):
                    if dx*dx + dy*dy <= stroke_w*stroke_w:
                        draw_text_track(td, (lx+dx, ly+dy), t, fo, tuple(stroke)+(255,), tracking)
            draw_text_track(td, (lx, ly), t, fo, tuple(fill)+(255,), tracking)
        else:
            td.text((lx, ly), t, font=fo, fill=tuple(fill)+(255,),
                    stroke_width=stroke_w, stroke_fill=tuple(stroke)+(255,))
    return total_h


def wordmark(base, x=40, y=34):
    d = ImageDraw.Draw(base)
    d.ellipse([x, y+8, x+14, y+22], fill=CY+(255,))
    d.text((x+24, y), "SIGNAL", font=font(FMB, 30), fill=INK+(255,))
    d.text((x+2, y+40), "EP.01 · INTERSTELLAR OBJECT 3I/ATLAS", font=font(FM, 15), fill=MUT+(255,))


def verdict_meter(base, corner="br", scale=1.0):
    mw, mh = int(360*scale), int(96*scale)
    m = Image.new("RGBA", (mw, mh), (0, 0, 0, 0))
    d = ImageDraw.Draw(m)
    d.rounded_rectangle([0, 0, mw-1, mh-1], radius=10, fill=(8, 12, 20, 220), outline=CY+(150,), width=2)
    d.text((16, 10), "VERDICT", font=font(FMB, 15), fill=MUT+(255,))
    d.text((mw-118, 12), "MOSTLY NOISE", font=font(FMB, 14), fill=NOISE+(255,))
    gx, gy, gw, gh = 16, 52, mw-32, 14
    for i in range(gw):
        t = i/gw
        r = int(46+(242-46)*t); g = int(224+(178-224)*t); b = int(232+(76-232)*t)
        d.line([(gx+i, gy), (gx+i, gy+gh)], fill=(r, g, b, 255))
    d.rectangle([gx, gy, gx+gw, gy+gh], outline=(40, 60, 80, 255), width=1)
    d.text((gx, gy+gh+2), "SIGNAL", font=font(FM, 12), fill=CY+(220,))
    tb = d.textbbox((0, 0), "NOISE", font=font(FM, 12))
    d.text((gx+gw-(tb[2]-tb[0]), gy+gh+2), "NOISE", font=font(FM, 12), fill=NOISE+(220,))
    nx = gx+int(gw*0.80)
    d.line([(nx, gy-6), (nx, gy+gh+6)], fill=INK+(255,), width=3)
    d.ellipse([nx-6, gy-14, nx+6, gy-2], fill=NOISE+(255,), outline=(8, 12, 20, 255), width=2)
    pad = 28
    pos = {"br": (W-mw-pad, H-mh-pad), "bl": (pad, H-mh-pad),
           "tr": (W-mw-pad, pad+70), "tl": (pad, pad+70)}[corner]
    base.alpha_composite(m, pos)


def qmark(base, x, y, size, color):
    lay = Image.new("RGBA", base.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(lay)
    fo = font(ANTON, size)
    d.text((x, y), "?", font=fo, fill=color+(255,), stroke_width=max(4, size//18), stroke_fill=(6, 8, 12, 255))
    g = lay.filter(ImageFilter.GaussianBlur(size//10))
    base.alpha_composite(g); base.alpha_composite(lay)


def target_circle(base, cx, cy, r, color, label=None):
    lay = Image.new("RGBA", base.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(lay)
    d.ellipse([cx-r, cy-r, cx+r, cy+r], outline=color+(255,), width=6)
    # ticks
    for ang in (0, 90, 180, 270):
        a = math.radians(ang)
        x1 = cx+math.cos(a)*(r-14); y1 = cy+math.sin(a)*(r-14)
        x2 = cx+math.cos(a)*(r+14); y2 = cy+math.sin(a)*(r+14)
        d.line([(x1, y1), (x2, y2)], fill=color+(255,), width=5)
    g = lay.filter(ImageFilter.GaussianBlur(6))
    base.alpha_composite(g); base.alpha_composite(lay)
    if label:
        dd = ImageDraw.Draw(base)
        fo = font(FMB, 22)
        tb = dd.textbbox((0, 0), label, font=fo)
        lx = cx-(tb[2]-tb[0])//2; ly = cy-r-40
        dd.rectangle([lx-10, ly-4, lx+(tb[2]-tb[0])+10, ly+30], fill=(6, 8, 12, 220))
        dd.text((lx, ly), label, font=fo, fill=color+(255,))


def arrow(base, x1, y1, x2, y2, color, w=12):
    lay = Image.new("RGBA", base.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(lay)
    d.line([(x1, y1), (x2, y2)], fill=color+(255,), width=w)
    ang = math.atan2(y2-y1, x2-x1)
    for s in (-0.5, 0.5):
        hx = x2-30*math.cos(ang+s); hy = y2-30*math.sin(ang+s)
        d.line([(x2, y2), (hx, hy)], fill=color+(255,), width=w)
    g = lay.filter(ImageFilter.GaussianBlur(5))
    base.alpha_composite(g); base.alpha_composite(lay)


# text box anchors: returns (x, y, box_w, box_h, align)
def textbox(pos):
    pad = 54
    boxes = {
        "tr":     (W-pad, 120, int(W*0.52), int(H*0.42), "right"),
        "tl":     (pad,   120, int(W*0.52), int(H*0.42), "left"),
        "bl":     (pad,   H-320, int(W*0.55), int(H*0.40), "left"),
        "br":     (W-pad, H-320, int(W*0.55), int(H*0.40), "right"),
        "bottom": (W//2,  H-300, int(W*0.86), int(H*0.34), "center"),
        "top":    (W//2,  90,  int(W*0.86), int(H*0.34), "center"),
        "center": (W//2,  H//2-120, int(W*0.80), int(H*0.44), "center"),
        "left":   (pad,   200, int(W*0.50), int(H*0.50), "left"),
        "right":  (W-pad, 200, int(W*0.50), int(H*0.50), "right"),
    }
    return boxes.get(pos, boxes["bl"])


def compose(spec, bg_path, out_path):
    bg = fit_bg(bg_path)
    bg = vignette(bg, spec.get("vignette", 0.5))
    scrim = spec.get("scrim", "bl")
    if scrim and scrim != "none":
        bg = side_scrim(bg, scrim, frac=spec.get("scrim_frac", 0.62), power=spec.get("scrim_power", 200))
    base = bg.convert("RGBA")

    # extras behind text
    for ex in spec.get("extras", []):
        t = ex["type"]
        if t == "circle":
            target_circle(base, ex["cx"], ex["cy"], ex["r"], COLORS.get(ex.get("color", "red"), COLORS["red"]), ex.get("label"))
        elif t == "arrow":
            arrow(base, ex["x1"], ex["y1"], ex["x2"], ex["y2"], COLORS.get(ex.get("color", "cyan"), CY))
        elif t == "qmark":
            qmark(base, ex["x"], ex["y"], ex.get("size", 340), COLORS.get(ex.get("color", "cyan"), CY))

    # headline
    hx, hy, bw, bh, align = textbox(spec.get("pos", "bl"))
    fo, lines, sz = autofit(spec["hook_text"].upper(), ANTON, bw, bh, start=spec.get("max_size", 210),
                            min_s=64, tracking=spec.get("tracking", 0))
    fill = COLORS[spec.get("hook_color", "white")]
    glow = COLORS[spec.get("glow_color", spec.get("hook_color", "cyan"))]
    th = glow_text(base, lines, fo, (hx, hy), fill, glow, align=align, tracking=spec.get("tracking", 0))

    # subtext
    sub = spec.get("subtext", "").strip()
    if sub:
        sfo = font(ARCHIVO, spec.get("sub_size", 34))
        d = ImageDraw.Draw(base)
        sw = line_w(sub.upper(), sfo, 2)
        sy = hy + th + 18
        if align == "center":   sx = hx - sw//2
        elif align == "right":  sx = hx - sw
        else:                   sx = hx
        d.rectangle([sx-14, sy-6, sx+sw+14, sy+spec.get("sub_size", 34)+14], fill=(6, 8, 12, 205))
        # accent tick
        d.rectangle([sx-14, sy-6, sx-8, sy+spec.get("sub_size", 34)+14], fill=CY+(255,))
        draw_text_track(d, (sx, sy), sub.upper(), sfo, INK+(255,), 2)

    wordmark(base)
    if spec.get("use_meter"):
        verdict_meter(base, corner=spec.get("meter_corner", "br"))

    out = base.convert("RGB")
    # export under 2MB
    q = 92
    out.save(out_path, "JPEG", quality=q, optimize=True)
    while os.path.getsize(out_path) > 2_000_000 and q > 70:
        q -= 4; out.save(out_path, "JPEG", quality=q, optimize=True)
    # also a 720p-safe png preview at half for quick view
    return os.path.getsize(out_path)


if __name__ == "__main__":
    specfile = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "thumbs.json")
    specs = json.load(open(specfile))
    for s in specs:
        bg = s["bg"] if os.path.isabs(s["bg"]) else os.path.join(HERE, s["bg"])
        out = os.path.join(HERE, s["out"])
        sz = compose(s, bg, out)
        print(f"{s['out']}: {sz//1024} KB  hook='{s['hook_text']}'  bg={os.path.basename(bg)}")
